### PR TITLE
Exclude OOIs creation from the OOI add form by OOI-types

### PR DESCRIPTION
**Pull request by Rieven**
### Changes
Exclude manual creation of OOI's with certain types. 

### Issue link

Closes ...

### Demo
These types are excluded from the ooi add form:
RESTAPI, Incident, ImageMetadata, Report, ReportData

image

### QA notes
Check if types are excluded and cannot manipulate ooi creation from URL at ooi add form
RESTAPI, Incident, ImageMetadata, Report, ReportData

image

---

### Code Checklist

- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue.
- [ ] I have written unit tests for the changes or fixes I made.
- [x] I have checked the documentation and made changes where necessary.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

- [x] Tickets have been created for newly discovered issues.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---

## Checklist for code reviewers:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---

## Checklist for QA:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by underdarknl** [comment]
I think this (and other lists) should be constructed from properties on the ooi-classes.

**Comment by Rieven** [comment]
> I think this (and other lists) should be constructed from properties on the ooi-classes.

So you mean that we add like a boolean property to the ooi like `manual_creation = False` ? Something like this?

**Comment by underdarknl** [comment]
Yup, and I'm guessing there's a few other properties that we want to add based on the other lists I see.
This would make sure we do our bookkeeping of all the traits in the OOI-classes themselves instead of somewhere else entirely.
If we build the lists dynamically when we need them, we don't have two spots in the codebase that are involved when someone wants to add an OOI-Type.
Currently, adding an OOI-Type means adding the OOi-Type itself, *and* changing a bunch of lists all over octopoes and Rocky to make the OOI valid according to pydantic, and or show up in the correct frontends.

**Comment by stephanie0x00** [comment]
## Checklist for QA:

- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
  - [x] I have managed to pass the onboarding flow
  - [x] Objects and Findings are created properly
  - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.
- [x] I checked the logs for errors and/or warnings and made issues where necessary

### What works:
Seems to work. 

### What doesn't work:
n/a

### Bug or feature?:
n/a

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
