### PR TITLE
update/nuclei path fix, backwards compat

### PR DESCRIPTION
**Pull request by RiieCco**
### Changes
Nuclei seem to love to change things that break the tool, I updated the templates path and the version.

### Code Checklist
- [x] All the commits in this PR are properly PGP-signed and verified;
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [x] I have written unit tests for the changes or fixes I made.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Review by ammar92 — APPROVED** [review]
Ah nice find. We had the same with the `kat_webpage_capture` plugin, even though we pinned the image, the container downloaded updates (`npm` packages) that broke stuff.

(Haven't tested this yet)

**Comment by underdarknl** [comment]
> Ah nice find. We had the same with the `kat_webpage_capture` plugin, even though we pinned the image, the container downloaded updates (`npm` packages) that broke stuff.
> 
> (Haven't tested this yet)

One more reason to pre-bake stable images of our boefjes. While updated functionality is nice, it also muddies the water in terms of 'what have you tested' which we cannot allow if we want to offer proof of what KAT did.

**Comment by RiieCco** [comment]
@underdarknl, i agree that from a compliance and stability perspective that makes most sense. In the context of 
Nuclei, it pulling all the templates for every scan it does also ensures that we have a better chance of discovering vulnerabilities sooner when we are not dependent the velocity of building new images.

Plus, this is Nuclei container specific behaviour that we can't control. Even when we do pin a Nuclei image (which i did) it always pulls the latest templates from their repo on start-up. So that makes it harder to counter.

**Comment by dekkers** [comment]
This also deletes the kat_nuclei boefje?

**Comment by RiieCco** [comment]
Hey @dekkers,

that is correct, kat_nuclei is the same as kat_nuclei_cve.
That is why i removed it :-)

**Review by dekkers — APPROVED** [review]

**Pull request merged**
