### PR TITLE
Convert `docker-compose` to `docker compose`

### PR DESCRIPTION
**Pull request by originalsouth**
### Changes
Convert all instances of `docker-compose` to `docker compose`.

### Issue link
Initial fix for #2336 (still experiencing race conditions)

### Demo
Conversion script
```
#!/usr/bin/env zsh

# Patch scripts without touching files or variables
for potato in $(rg -l "docker-compose")
do
    sed -i 's/docker-compose -\([a-z]\)/docker compose -\1/g' $potato
    sed -i 's/docker-compose \([a-z]*[a-z]\)/docker compose \1/g' $potato
done

# Probably we do not want to touch release notes
git checkout docs/source/release_notes/1.8.rst
```
`rg` can be found [here](https://github.com/BurntSushi/ripgrep).

---

### Code Checklist
- [x] All the commits in this PR are properly PGP-signed and verified;
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by originalsouth** [comment]
Well, at least the failure is consistent now with my observations at home...
```
...
 ------------------------------------------------------------------------------
Robot.07 Bit Configs                                                  | PASS |
2 tests, 2 passed, 0 failed
==============================================================================
Robot.07 Rerun Bits                                                           
==============================================================================
Rerun bits                                                            | FAIL |
2 != 3
------------------------------------------------------------------------------
Robot.07 Rerun Bits                                                   | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
Robot.08 Findings                                                             
==============================================================================
List Findings                                                         | PASS |
------------------------------------------------------------------------------
Robot.08 Findings                                                     | PASS |
1 test, 1 passed, 0 failed
==============================================================================
Robot                                                                 | FAIL |
15 tests, 14 passed, 1 failed
==============================================================================
...
```
Snip from [here](https://github.com/minvws/nl-kat-coordination/actions/runs/7552713085/job/20562097290?pr=2341).

**Review by ammar92 — APPROVED** [review]
Probably not the solution for the root problem, but definitely the recommended approach for current and newer Docker installations

**Comment by originalsouth** [comment]
@ammar92 @dekkers @underdarknl do we also want to update the github pipelines (`docker-compose` to `docker compose`)?

**Comment by dekkers** [comment]
> @ammar92 @dekkers @underdarknl do we also want to update the github pipelines (`docker-compose` to `docker compose`)?

Yes, those should also be updated.

**Comment by originalsouth** [comment]
> Yes, those should also be updated.

Done

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
