### PR TITLE
Fix enabling normalizers from Rocky

### PR DESCRIPTION
**Pull request by Donnype**
### Changes

_Please describe the essence of this PR in a few sentences. Mention any breaking changes or required configuration steps._

### Issue link

-

### Demo

image

### QA notes

Please test that you can enable and disable normalizers!

---

### Code Checklist

- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue.
- [x] I have written unit tests for the changes or fixes I made.
- [x] I have checked the documentation and made changes where necessary.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

---

## Checklist for code reviewers:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---

## Checklist for QA:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Review by ammar92 — DISMISSED** [review]

**Comment by stephanie0x00** [comment]
## Checklist for QA:

- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [ ] I confirmed that there are no unintended functional regressions in this branch:
  - [x] I have managed to pass the onboarding flow
  - [ ] Objects and Findings are created properly
  - [ ] Tasks are created and completed properly
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.
- [ ] I checked the logs for errors and/or warnings and made issues where necessary

### What works:
Normalizers (and boefjes) run when they weren't disabled. 

### What doesn't work:
When re-enabling the normalizer it doesn't seem to rerun. 

Steps to reproduce: 
- Go through the onboarding
- Disable nmap normalizer
- Enable nmap tcp and let it run against your host. 
- Observe that the nmap normalizer doesn't run. 
- Enable the nmap normalizer.
- Observe that it didn't rerun
- Click the rerun all bits button and observe that the nmap normalizer didnt run again. 


### Bug or feature?:
See above

**Comment by Donnype** [comment]
@stephanie0x00 I don't think we schedule normalizers when they've only been enabled. @jpbruinsslot?

**Comment by jpbruinsslot** [comment]
> @stephanie0x00 I don't think we schedule normalizers when they've only been enabled. @jpbruinsslot?

You are correct. Normalizers won't run based on being enabled. Either they have to be explicitly told to rerun, or they run based on raw file received event from bytes.

**Comment by stephanie0x00** [comment]
## Checklist for QA:

- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
  - [x] I have managed to pass the onboarding flow
  - [x] Objects and Findings are created properly
  - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.
- [x] I checked the logs for errors and/or warnings and made issues where necessary

### What works:
Normalizers (and boefjes) run when they (weren't) disabled. The disabled normalizer runs again when it is disabled and triggered by the corresponding boefje. 

### What doesn't work:
n/a

### Bug or feature?:
n/a

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
