### PR TITLE
Do not store the hypothetically produced mime-types always

### PR DESCRIPTION
**Pull request by Donnype**
### Changes

This is a bug introduced during the create/copy boefje feature, where I needed to start searching for non-local plugins in the job handler. Here I joined - although still unclear to my why I did this - the `plugin.produces` mime-types always, but this is a large list for **only** the webpage-analysis boefje, meaning we get issues where the saved files had the same big list of mime-types, Bytes deduplicating on the mime-type set as expected. I [realised this](https://github.com/minvws/nl-kat-coordination/pull/3400#discussion_r1741642459) at one point but perhaps didn't see the harm. The irony.

### Issue link

Closes https://github.com/minvws/nl-kat-coordination/issues/3570

### Demo

-

### QA notes

Should resolve the issue described in https://github.com/minvws/nl-kat-coordination/issues/3570

---

### Code Checklist

- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue.
- [x] I have written unit tests for the changes or fixes I made.
- [x] I have checked the documentation and made changes where necessary.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

---

## Checklist for code reviewers:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---

## Checklist for QA:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by noamblitz** [comment]
Im missing the default mimetypes now: `"mime_types": [{"value": "openkat-http/response"}]`. I would expect boefje/webpage-analysis to also be available as mimetype.

**Comment by Donnype** [comment]
@noamblitz, strange, I do have the default mime-types:
image

**Comment by noamblitz** [comment]
Boefjes that do not return mimetypes in their boefje now also do not seem to stop running and fail after a while.

**Comment by noamblitz** [comment]
> @noamblitz, strange, I do have the default mime-types: image

Yeah these are the ones that you get when boefjes fail right.

**Comment by noamblitz** [comment]
Seems to work corectly now again!

**Review by ammar92 — APPROVED** [review]
No remarks

**Comment by underdarknl** [comment]
> Bytes deduplicating on the mime-type set as expected.

This is not What I'd expect to be honest. If a boefje creates 4 raw files, all with the same mime-types (or none). I'd expect there to be 4 raw files attached to the boefje-job.
Granted, this does make it hard to differentiate those raw files in the UX, as they dont have a name, but thats a problem for another day.

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
