### PR TITLE
Fix/2721 improve error handling by better exception aggregation v2

### PR DESCRIPTION
**Pull request by originalsouth**
See #2760 but now with a cooler branch name.

### CODE REVIEW

**Comment by ammar92** [comment]
Can we please rename the branch instead of duplicating PRs? Duplicating PRs can lead to confusion and loss of context. Also, since we do squash merges for main, the branch name may not appear in the main tree anyways.

**Comment by originalsouth** [comment]
> Can we please rename the branch instead of duplicating PRs? Duplicating PRs can lead to confusion and loss of context. Also, since we do squash merges for main, the branch name may not appear in the main tree anyways.

I agree, but https://stackoverflow.com/questions/20007578/renaming-a-branch-while-on-pull-request

**Comment by ammar92** [comment]
> > Can we please rename the branch instead of duplicating PRs? Duplicating PRs can lead to confusion and loss of context. Also, since we do squash merges for main, the branch name may not appear in the main tree anyways.
> 
> I agree, but https://stackoverflow.com/questions/20007578/renaming-a-branch-while-on-pull-request

That's unfortunate, I've been going through the GitHub docs for renaming branches and indeed, if the renamed branch is the head branch of an open pull request, this pull request is closed.

If it's merely about the branch name, then I suggest to close this PR. Sure a nicer branch name would've been good from the start, but renaming it at this stage doesn't add anything anymore imho.

**Comment by originalsouth** [comment]
@ammar92 @stephanie0x00 both this PR #2795 and #2760 contain the same patches. I really have no opinion on which one should be merged and which one should be closed. As far as I am aware we have no policy or guidelines on branch name naming and as mentioned after squashing there should be no difference. Both remain open for now, and I am happy with either one being merged or rejected.

**Pull request merged**
