### PR TITLE
Remove default setting of id to None

### PR DESCRIPTION
**Pull request by jpbruinsslot**
### Changes

Remove default setting of id to None. Since pydantic 2.0 setting an optional field that is not required, a None value is suggested as default however creating a new instance will create this default value.

### Issue link

Closes https://github.com/minvws/nl-kat-coordination/issues/2161

### CODE REVIEW

**Review by ammar92 — APPROVED** [review]

**Review by ammar92 — APPROVED** [review]

**Comment by underdarknl** [comment]
I think we use the Id's on various pages to allow the user to 'inspect' or 'download the raw files' for any given job, right? So removing them would be unwise. 
It would be more obvious if the save/create endpoints on the scheduler just don't accept these id's or clean them out. Or, if we do want to clean them in Rocky, we do so before sending the model out to the scheduler.

**Comment by jpbruinsslot** [comment]
Yeah think we need to do the same as in the scheduler make seperate request and response models

**Comment by underdarknl** [comment]
Im not sure. The scheduler picks up the job from Rocky Just fine. It creates it, and dispenses it to the worker. However, the worker receives this Job with an ID of None as opposed to a UUID as what the scheduler does for its own jobs. Maybe we just need to fill in the null value in the scheduler, regardless of where the job came from (rocky vs the scheduler itself)

**Comment by underdarknl** [comment]
Getest: 
ik kan reschedulen, schedulen vanaf de object page, en schedulen vanaf de boefje page.  
Ook kan ik bij zowel normalisers als boefjes de raw file downloaden.

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
