### PR TITLE
Improved poetry configuration for keiko and octopoes

### LINKED ISSUE #735: Unified approach to dependency management (`requirements.txt`)
**Is your feature request related to a problem? Please describe.**
Currently, we have no standardized approach to dependency management in the various modules, aside from that we use `pip`'s `requirements.txt`.

**Describe the solution you'd like**
Some things worth considering:

- Using Poetry and a lock file (implemented in Keiko and Octopoes by @Lisser)
    - Has some nice features for managing `venv`s as well   
- A single top-level `requirements.txt` instead of per module
    - How would this impact the ability to package and run the modules in this repository individually?
- How to distinguish between production/development/CI dependencies (e.g. linters)?
    - Currently, we use seperate requirements files
- How can we do this in such a way that we have minimal extra work for Debian packaging?
- Integration with dependabot is definitely nice to have

**Additional context**
https://github.com/minvws/nl-kat-coordination/pull/729

### PR DESCRIPTION
**Pull request by Darwinkel**
### Changes
Improves the pipeline for managing dependencies through poetry. I constrained this PR to refactoring keiko and octopoes, since those modules already use poetry. After this PR, we can roll it out to the other modules.

Also, I removed some of the tooling config from the octopoes/keiko pyproject.toml's as those configs are centrally managed by pre-commit through the root's pyproject.toml, and upgraded some workflows to Python 3.11.

### Issue link
Relates to #735  (third attempt :-))

### Proof
See CI.

---

### Code Checklist
- [x] All the commits in this PR are properly PGP-signed and verified;
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by Darwinkel** [comment]
Some notes with regards to the feedback from the previous PR's:
- Dynamic versioning (https://github.com/minvws/nl-kat-coordination/pull/1038#discussion_r1205432390) appears to be non-trivial: https://pypi.org/project/poetry-dynamic-versioning/
- The yml linter complains when applying path filtering in the style of `**/requirements*.txt`

**Comment by Darwinkel** [comment]
Ah, interesting. The CI automatically updates point releases. We should probably pin point releases in `pyproject.toml`.

**Comment by Darwinkel** [comment]
> Ah, interesting. The CI automatically updates point releases. We should probably pin point releases in `pyproject.toml` to prevent that. Probably also better for dependabot.

>The yml linter complains when applying path filtering in the style of **/requirements*.txt

Fixed!

**Review by ammar92 — DISMISSED** [review]

**Review by praseodym — DISMISSED** [review]

**Comment by praseodym** [comment]
I'd say this PR shouldn't close #735 because it only changes Keiko and Octopoes, not the other services. We'll want to change those as part of #735 too.

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
