### PR TITLE
Fixes notification alignment

### PR DESCRIPTION
**Pull request by HeleenSG**
### Changes
- Fixes alignment issue in inline notifications. 

### Issue link

Alignment issue within notifications: 
Screenshot 2024-09-12 at 11 54 18

_Please add the link to the issue after "Closes"._

Closes https://github.com/minvws/nl-kat-coordination/issues/3502

### Demo
Inline (p, span etc) 
Screenshot 2024-09-11 at 17 56 18

Block notifications: 
Screenshot 2024-09-11 at 17 58 12

### QA notes

- Please check in multiple places if all types are working correctly.

---

### Code Checklist

- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue.
- [x] I have written unit tests for the changes or fixes I made.
- [x] I have checked the documentation and made changes where necessary.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

- [x] Tickets have been created for newly discovered issues.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---

## Checklist for code reviewers:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---

## Checklist for QA:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by underdarknl** [comment]
Code looks good to me.

**Comment by stephanie0x00** [comment]
A few unexpected situations were found:  
- Clicking the Add indemnification button on the Settings page
- In the onboarding the confirmation message is smaller. This also happens when adding a new organisation. 

image

image

**Comment by HeleenSG** [comment]
Known issue in this pr: The width of the notifications are sometimes smaller than the width of input fields. This will be fixed within the form styling pr. As the issue is the width of the input rather than the width of the notification. So it can be ignored within this pr.

**Comment by stephanie0x00** [comment]
All the changes look good. All the notification windows that were funky that were identified now look good.

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
