### PR TITLE
Adds loggers to report flow

### PR DESCRIPTION
**Pull request by madelondohmen**
### Changes
This PR adds some loggers to the report flow.
Event codes can be found here: https://github.com/minvws/nl-kat-coordination/issues/3043#issuecomment-2173392197

### Issue link
Closes ...

### QA notes

_Please add some information for QA on how to test the newly created code._

---

### Code Checklist

- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue.
- [ ] I have written unit tests for the changes or fixes I made.
- [x] I have checked the documentation and made changes where necessary.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

- [ ] Tickets have been created for newly discovered issues.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---

## Checklist for code reviewers:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---

## Checklist for QA:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Review by ammar92 — COMMENTED** [review]
I suggest looking at the code base on how we currently deal with the logs and event codes. See for example the constants defined in `octopoes/octopoes/types.py`, similar constants can be defined in `rocky/reports/views/mixins.py` and `rocky/rocky/scheduler.py`. Also note that event codes are currently implemented as integers, so prefixing with 0 and sending them out as strings is wrong. For example and in the style of the already existing logs, `"080071"` would be something like `800071`

**Comment by madelondohmen** [comment]
> I suggest looking at the code base on how we currently deal with the logs and event codes. See for example the constants defined in `octopoes/octopoes/types.py`, similar constants can be defined in `rocky/reports/views/mixins.py` and `rocky/rocky/scheduler.py`. Also note that event codes are currently implemented as integers, so prefixing with 0 and sending them out as strings is wrong. For example and in the style of the already existing logs, `"080071"` would be something like `800071`

@ammar92 This was based on a conversation with @underdarknl, who said that the event codes had to be strings instead of integers and that they had to start with a "0" (like how it's written here https://github.com/minvws/nl-kat-coordination/issues/3043#issuecomment-2173392197). @underdarknl, what do you think?

**Comment by stephanie0x00** [comment]
Moved from QA to blocked as it's waiting for input from @underdarknl .

**Comment by underdarknl** [comment]
Lets continue with Integers for now. The spec mentions 'codes', the examples have Codes with a leading zero, but beyond that there's no immediate value to making them into strings I think.

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
