### PR TITLE
Add why container stdout/stderr can't be used for boefjes output

### PR DESCRIPTION
**Pull request by dekkers**
### Changes
This adds information why container stdout/stderr can't be used for boefjes output to the boefjes runner design document so it is clear for everybody.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Review by ammar92 — APPROVED** [review]
Clear

**Comment by underdarknl** [comment]
Would'nt the http upload integration be part of the outer layer of the boefje, Eg Boefjes now have a run() method, which returns the raw files. The http uploading would need to be done *in* the container, and not in the runner, since there is no way of getting this data cleanly out of the boefje and into that uploader.

**Comment by stephanie0x00** [comment]
The only thing not clear for me is the following part. Why shouldn't this be done with OpenKAT? 

> This is something that can be done with a cluster component like filebeat, but must not be done with an application like OpenKAT.

**Comment by dekkers** [comment]
> The only thing not clear for me is the following part. Why shouldn't this be done with OpenKAT?
> 
> > This is something that can be done with a cluster component like filebeat, but must not be done with an application like OpenKAT.

I added a bit more detail, so I hope it is clear now.

**Comment by stephanie0x00** [comment]
Yes thanks :+1:

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
