### PR TITLE
OOI selection at Aggregate report does not remember changed selection

### PR DESCRIPTION
**Pull request by Rieven**
### Changes
Remove form fields for objects selection as this is the first step and must override selection when going back.

### Issue link
https://github.com/minvws/nl-kat-coordination/issues/2618

Closes https://github.com/minvws/nl-kat-coordination/issues/2618

### Demo
_Please add some proof in the form of screenshots or screen recordings to show (off) new functionality, if there are interesting new features for end-users._

---

### Code Checklist
- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have made corresponding changes to the documentation, if necessary.
- [x] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Review by ammar92 — CHANGES_REQUESTED** [review]
How does this work? I don't see any validation of this variable. Based on the condition check in `report_form_fields.html` "no" (or any other non-empty string) would also render the hidden inputs. You probably meant to use `False`

**Comment by Rieven** [comment]
> How does this work? I don't see any validation of this variable. Based on the condition check in `report_form_fields.html` "no" (or any other non-empty string) would also render the hidden inputs. You probably meant to use `False`

Yes, the idea is to hide the ooi selection for this particular template, I can indeed set any non-empty like you said or I can mak it more concrete here, put a value that it checks upon. I will make it then a boolean.

**Comment by underdarknl** [comment]
Instead of a new var, couldn't you just set oois to none?

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
Seems to work as expected, both in the normal and aggregate report flow. I've tested by selecting one or more objects, clicking on the next page, then click previous again and change the selection. Tested with the 'select all' functionality, single OOI and with multiple OOIs. The aggregate report can also be generated and it has the selected objects under 'Assets overview'.

### What doesn't work:
* _bullet point + screenshot (if useful) per tested functionality_

### Bug or feature?:
* _bullet p

**Review by dekkers — APPROVED** [review]

**Pull request merged**
