### PR TITLE
Remove old Findings Report

### LINKED ISSUE #3500: wrong encoding links to background info in report leads to 404-pages
_Please add `bug`, the name of any relevant modules (e.g. `rocky`), and any other relevant labels to your issue._

**Describe the bug**
In a finding report in PDF-format the user can click on a link to get more background info about the finding. The linktext is correct, the href is wrong and ends in a 404. For example: https://developer.mozilla.org/en%7B-%7DUS/docs/Web/HTTP/CSP which must be https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP.

Same applies for these links:
https://developer.mozilla.org/en%7B-%7DUS/docs/Web/HTTP/Headers/Strict%7B-%7DTransport%7B-%7DSecurity
https://developer.mozilla.org/en%7B-%7DUS/docs/Web/HTTP/Headers/Permissions%7B-%7DPolicy
https://developer.mozilla.org/en%7B-%7DUS/docs/Web/HTTP/Headers/X%7B-%7DDNS%7B-%7DPrefetch%7B-%7DControl
https://owasp.org/www%7B-%7Dproject%7B-%7Dsecure%7B-%7Dheaders/#div{-}headers

Those where the findings in one report.

**To Reproduce**
General behaviour/info, nothing local so i presume any download of a findings report. I did not check other MDN links 

**Expected behavior**
is opening the correct webpage, preferable in a new tab but that is probably a new ticket.

**Screenshots**

**OpenKAT version**
1.16

**Desktop (please complete the following information if relevant):**

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Additional context**

### PR DESCRIPTION
**Pull request by madelondohmen**
### Changes

This PR fixes the old "Download PDF" button on the Findings page, which redirected to the old OOI Report. 
This report doesn't exist anymore in the new flow.

We decided to delete the button completely, until we've created the new report flow. It just doesn't make sense to put a "Generate Findings Report" here, which redirects you to the Generate Report flow with ALL ooi's selected for the Finding Report type. And currently there's no easy way to not select ALL objects. 

What this PR does:
- Remove the button on the Findings Page
- Remove `ooi_report.py`, `ooi_report.html` and `ooi_report_404.html`
- Remove the corresponding URLs
- Remove the corresponding tests
- Remove mock from conftest.py
- Add "Source" to new Findings Report
- Change the input_ooi_types in FindingsReport (it used to be ALL_TYPES, but now excludes some types)

### Issue link
Closes #3500

### Demo
afbeelding

### QA notes
- Go to Findings page
- "Download PDF" button should be removed
- Generate the report

### New tickets
#3578 

---

### Code Checklist

- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue.
- [ ] I have written unit tests for the changes or fixes I made. // Removed redundant unit tests
- [x] I have checked the documentation and made changes where necessary.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

- [ ] Tickets have been created for newly discovered issues.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---

## Checklist for code reviewers:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---

## Checklist for QA:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Review by ammar92 — APPROVED** [review]
Looks good to me 👍

**Comment by stephanie0x00** [comment]
QA notes:

The current selection of selected items is a bit too broad, as this also includes actual findings (eg. jQuery versions). This should be reduced to hosts only. 

image

**Comment by madelondohmen** [comment]
> QA notes:
> 
> The current selection of selected items is a bit too broad, as this also includes actual findings (eg. jQuery versions). This should be reduced to hosts only.
> 

This shouldn't be a problem anymore, since the button has been removed completely.

**Comment by TwistMeister** [comment]
## Checklist for QA:

- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
  - [x] I have managed to pass the onboarding flow
  - [x] Objects and Findings are created properly
  - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.
- [x] I checked the logs for errors and/or warnings and made issues where necessary

I didn't find anything unusual when creating a findings report using the report flow nor did I when generating a report from a findings detail page.

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
