### PR TITLE
Add rocky worker service to debian packages

### PR DESCRIPTION
**Pull request by Donnype**
### Changes

This step should add the rocky worker service to the Debian packages as well.

### Issue link

-

### Demo

-
### QA notes

We should test the report generation flow on a Debian installation. Edit: @dekkers offered help in the comments below with testing the Debian packages and production docker setup if needed :pray: 

---

### Code Checklist

- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue.
- [ ] I have written unit tests for the changes or fixes I made.
- [x] I have checked the documentation and made changes where necessary.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

---

## Checklist for code reviewers:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---

## Checklist for QA:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by underdarknl** [comment]
Good catch!

**Comment by dekkers** [comment]
We should also add this to docker-compose.release-example.yml and https://docs.openkat.nl/installation_and_deployment/containers.html#container-commands and create an entrypoint so you can specify a simple CMD like we do for boefjes and octopoes containers. This also gives us the freedom to easily change the worker command in the future.

**Review by ammar92 — DISMISSED** [review]
No remarks

**Comment by dekkers** [comment]
LGTM, moved to QA. Let me know if any help is needed with testing the Debian or example production container setup.

**Comment by dekkers** [comment]
I deployed the Debian packages and created a scheduled report. With the fixes I have already pushed the rocky worker starts and fetches the scheduled report job.

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
