### PR TITLE
Support setting a custom JSON schema for copied boefjes

### PR DESCRIPTION
**Pull request by Donnype**
### Changes

This PR adds a "schema" field to the boefje database models so that we can also change the schema for copied (or new) boefjes. This was still lacking in the current APIs.

### Issue link

Closes https://github.com/minvws/nl-kat-coordination/issues/3052

### Demo

image

### QA notes

Again this is a migration mostly so: check out main, enable dns-records, check out this branch and verify that dns-records is still enabled:
```shell
git checkout main
# enable dns-records, change "test" to your own organisation id
curl -X PATCH -H 'Content-Type: application/json' --data-raw '{"enabled": true}' 'http://localhost:8003/v1/organisations/test/plugins/dns-records'
git checkout feature/add-json-schema-for-copied-boefjes
make kat
curl 'http://localhost:8003/v1/organisations/test/plugins/dns-records' | jq
# Expected: "enabled": true and a new "schema" field 
``` 

Edit: Verify that the migration ran successfully. The output of the command below should be `5be152459a7b`
```
docker compose exec -u postgres postgres /bin/bash -c 'psql -U $POSTGRES_USER -d katalogus -c "SELECT * FROM public.alembic_version;"'
```

---

### Code Checklist

- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue.
- [x] I have written unit tests for the changes or fixes I made.
- [x] I have checked the documentation and made changes where necessary.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---

## Checklist for code reviewers:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---

## Checklist for QA:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by dekkers** [comment]
Looks good to me, can be moved to QA if no one else has any code review feedback.

**Comment by stephanie0x00** [comment]
## Checklist for QA:

- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [ ] I confirmed that there are no unintended functional regressions in this branch:
  - [ ] I have managed to pass the onboarding flow
  - [ ] Objects and Findings are created properly
  - [ ] Tasks are created and completed properly
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.
- [ ] I checked the logs for errors and/or warnings and made issues where necessary

### What works:
Unsure yet. 

### What doesn't work:
The migration breaks things. There are some SQL errors in the log files, logs are shared with @Donnype 
One of the commands from the QA notes `curl -X PATCH -H 'Content-Type: application/json' --data-raw '{"enabled": true}' 'http://localhost:8003/v1/organisations/test/plugins/dns-records'` doesn't give output. It's unclear whether or not this is intentional. 

### Bug or feature?:
Unsure yet.

**Comment by Donnype** [comment]
Haven't been able to find logs of the migration itself, so perhaps that wasn't triggered somehow. We should perhaps rerun the flow and verify the migration was triggered. Also there should indeed be no response body returned from the curl command. TBC!

**Comment by madelondohmen** [comment]
## Checklist for QA:

- [x] I have checked out this branch, and successfully ran a fresh `make reset`. --> I did a "make kat" like in the QA notes
- [ ] I confirmed that there are no unintended functional regressions in this branch:
  - [ ] I have managed to pass the onboarding flow
  - [ ] Objects and Findings are created properly
  - [ ] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.
- [ ] I checked the logs for errors and/or warnings and made issues where necessary

### What works:
I've only tested the QA notes.
-  ``docker compose exec -u postgres postgres /bin/bash -c 'psql -U $POSTGRES_USER -d katalogus -c "SELECT * FROM public.alembic_version;"'`` gives back 5be152459a7b
- Checked out to checkout feature/add-json-schema-for-copied-boefjes, did "make kat" and ``curl 'http://localhost:8003/v1/organisations/test/plugins/dns-records'`` shows "enabled=true" and contains a "schema"

### What doesn't work:
N/A

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
