### PR TITLE
Load mermaid.js locally

### PR DESCRIPTION
**Pull request by Darwinkel**
## Changes
Currently, `sphinx` and `sphinxcontrib-mermaid` load the latest `mermaid.js` version from unpkg. Unfortunately, v10 has breaking changes which are currently incompatible with sphinxcontrib-mermaid. 

This PR loads a local `mermaid.min.js(.map)`, which is both more privacy friendly for our users as well as giving us more explicit control about the versioning of this library. 

## Issue ticket number and link
Linked directly.

## Proof
Trivial. See attached artifact.

image

## Checklist for author(s):
- [x] All the commits in this PR are properly PGP-signed and verified;
- [x] This PR comes from a `feature` or `hotfix` branch, in line with our git branching strategy;
- [x] This PR is "bite-sized" and only focuses on a single issue, problem, or feature;
- [x] I am not reinventing the wheel: there is no high-quality library that already has this feature;
- [x] I have changed the example `.env` files if I added, removed, or changed any config options, and I have informed others that they need to modify their `.env` files if required;
- [x] I have performed a self-review of my own code;
- [x] I have commented my code, particularly in hard-to-understand areas;
- [ ] I have made corresponding changes to the documentation, if necessary;
- [ ] I have written unit, integration, and end-to-end tests for the change that I made;

If a non-trivial PR:
- [ ] This PR is part of a milestone and has appropriate labels;
- [x] This PR is properly linked to the project board (either directly or via an issue);
- [x] I have added screenshots or some other proof that my code does what it is supposed to do;

```
## Checklist for functional reviewer(s):
- [ ] If a non-trivial PR: This PR is properly linked to an issue on the project board;
- [ ] I have checked out this branch, and successfully ran `make kat`;
- [ ] I have ran `make test-rf` and all end-to-end Robot Framework tests pass;
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended;
- [ ] I confirmed that there are no unintended functional regressions in this branch;

### What works:
* _bullet point + screenshot (if useful) per tested functionality_

### What doesn't work:
* _bullet point + screenshot (if useful) per tested functionality_

### Bug or feature?:
* _bullet point + screenshot (if useful) if it is unclear whether something is a bug or an intended feature._
```

```
## Checklist for code reviewer(s):
- [ ] The code passes the CI tests and linters;
- [ ] The code does not bypass authentication or security mechanisms;
- [ ] The code does not introduce any dependency on a library that has not been properly vetted;
- [ ] The code does not violate Model-View-Template and our other architectural principles;
- [ ] The code contains docstrings, comments, and documentation where needed;
- [ ] The code prioritizes readability over performance where appropriate;
- [ ] The code conforms to our agreed coding standards.
```

### CODE REVIEW

**Comment by Darwinkel** [comment]
Request for comments: the disadvantage of this approach is that we load 10mb of static files into the git repository. A bit much maybe?

**Comment by underdarknl** [comment]
Loading anything from unpkg.com is a security issue if you ask me, as unpkg.com would then need to be included in the CSP headers. unpkg.com in nature allows anyone to link to any project on NMP: "Use it to quickly and easily load any file from any package using a URL like:"
This in effect allow-lists the whole planet in your CSP.  And I would want to go so far as to introduce a BIT in OpenKAT which signifies as much when we see these domains listed in a CSP header.

Do we also need the map file in our repos, as that is only used for debugging I'd say?

**Comment by underdarknl** [comment]
See also: 
https://github.com/minvws/nl-kat-coordination/issues/107

**Comment by Darwinkel** [comment]
Removing the `.map` file reduces the file size to ~2.8mb, that's acceptable I guess.

**Review by Lisser — APPROVED** [review]

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
