### PR TITLE
Show plugin name in task list instead of plugin ID

### PR DESCRIPTION
**Pull request by Rieven**
### Changes
- Scheduler changes to show boefje name in frontend done in : https://github.com/minvws/nl-kat-coordination/pull/1693
- Change template to fetch plugin name instead of plugin id
- Added backwards compatibility for tasks that has been already runned and instead of None show at least the plugin ID till a new task is runned, it will then use the plugin name.
- `make kat` is needed to review 

### Issue link
https://github.com/minvws/nl-kat-coordination/issues/1365

Closes https://github.com/minvws/nl-kat-coordination/issues/1365

### Proof
Old and new tasks
image

---

### Code Checklist
- [x] All the commits in this PR are properly PGP-signed and verified;
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Review by ammar92 — CHANGES_REQUESTED** [review]
Can't reproduce this for old and new tasks
image

i put it in the description to run a `make kat`

**Comment by praseodym** [comment]
Why does the scheduler need changes to support this? Can't we do the lookup directly in Rocky, using the boefje id to get the boefje name from Katalogus?

**Comment by Rieven** [comment]
> Why does the scheduler need changes to support this? Can't we do the lookup directly in Rocky, using the boefje id to get the boefje name from Katalogus?

It can but then we need to loop over Boefjes objects to do a lookup, where the Scheduler can directly parse it.

**Comment by praseodym** [comment]
> It can but then we need to loop over Boefjes objects to do a lookup, where the Scheduler can directly parse it.

We could get the boefjes from the katalogus, create a dict with boefje id -> boefje name, and use that for each task?

**Comment by Rieven** [comment]
> > It can but then we need to loop over Boefjes objects to do a lookup, where the Scheduler can directly parse it.
> 
> We could get the boefjes from the katalogus, create a dict with boefje id -> boefje name, and use that for each task?

I would say that if the Scheduler is already shipping the whole Boefje object back to rocky, that it can at the same time ship it with the name. I will need to do another query to KAT-alogus.

**Comment by ammar92** [comment]
> i put it in the description to run a `make kat`

Yep I got that and that's the first ding I did after checking out this branch

**Comment by Darwinkel** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
* Backwards compatibility on old data
 image
* Also works on a fresh install
* No apparent regressions

**Review by ammar92 — APPROVED** [review]

**Review by dekkers — APPROVED** [review]

**Pull request merged**
