### PR TITLE
Scheduler optimizations implementation

### LINKED ISSUE #1797: Scheduler gets timeouts requesting token from Bytes
```
Could not check if task is running: id='8b9ad66acf63429aa5a3daf2a289200b' boefje=Boefje(id='dns-sec', version=None) input_ooi='Hostname|internet|REDACTED' organization='REDACTED' dispatches=[] [organisation_id=REDACTED, scheduler_id=boefje-REDACTED, caller=push_tasks_for_new_boefjes]
Traceback (most recent call last):
  File "/var/www/scheduler_v1.11/scheduler/connectors/services/bytes.py", line 20, in wrapper
    return function(self, *args, **kwargs)
  File "/var/www/scheduler_v1.11/scheduler/connectors/errors.py", line 14, in inner_function
    return func(*args, **kwargs)
  File "/var/www/scheduler_v1.11/scheduler/connectors/services/bytes.py", line 87, in get_last_run_boefje
    self._verify_response(response)
  File "/var/www/scheduler_v1.11/scheduler/connectors/services/bytes.py", line 58, in _verify_response
    response.raise_for_status()
  File "/var/www/html/.venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: REDACTED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/html/.venv/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/var/www/html/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='REDACTED', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/scheduler_v1.11/scheduler/schedulers/boefje.py", line 501, in push_task
    is_running = self.is_task_running(task)
  File "/var/www/scheduler_v1.11/scheduler/schedulers/boefje.py", line 433, in is_task_running
    raise exc_bytes
  File "/var/www/scheduler_v1.11/scheduler/schedulers/boefje.py", line 418, in is_task_running
    task_bytes = self.ctx.services.bytes.get_last_run_boefje(
  File "/var/www/scheduler_v1.11/scheduler/connectors/services/bytes.py", line 25, in wrapper
    self.login()
  File "/var/www/scheduler_v1.11/scheduler/connectors/services/bytes.py", line 54, in login
    self.headers.update({"Authorization": f"bearer {self._get_token()}"})
  File "/var/www/scheduler_v1.11/scheduler/connectors/services/bytes.py", line 62, in _get_token
    response = self.post(
  File "/var/www/scheduler_v1.11/scheduler/connectors/services/services.py", line 137, in post
    response = self.session.post(
  File "/var/www/html/.venv/lib/python3.8/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/var/www/html/.venv/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/www/html/.venv/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/www/html/.venv/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='REDACTED', port=443): Read timed out. (read timeout=5)
```

### PR DESCRIPTION
**Pull request by jpbruinsslot**
### Changes

* Added load tester script, allows us to create large quantities of organizations, ooi's, jobs to be executed.
* Added `threading.Lock` for `collect_metrics()` in `app.py`. Could potentially create a race condition when executing the `collect_metrics()` when organisations were added and removed.
* Added `threading.Lock` in the bytes service for the request headers update when requesting a new token
* Add configurable timeouts, pool connections for every external service connection. Also increased the default value of the timeout from 5 to 10.

### Closes

#1797

### CODE REVIEW

**Review by Donnype — APPROVED** [review]
It would be nice to have a more structured way to do benchmarking. For instance, I'd opt for adding an integration test that executes your load script. However, this might require setting up more service-wide integration tests of course..

But then we could just mark these tests using `pytest.mark.benchmark` or `pytest.mark.performance` and configure pytest to either always skip these unless explicitly targeted, or skip them when some file with a lot of test data (organizations, jobs etc.) is not present. Then we can start keeping track of the performance over time and see the impact of changes more consistently, especially if we always take the performance results of the github actions?

**Comment by jpbruinsslot** [comment]
> It would be nice to have a more structured way to do benchmarking. For instance, I'd opt for adding an integration test that executes your load script. However, this might require setting up more service-wide integration tests of course..
> 
> But then we could just mark these tests using `pytest.mark.benchmark` or `pytest.mark.performance` and configure pytest to either always skip these unless explicitly targeted, or skip them when some file with a lot of test data (organizations, jobs etc.) is not present. Then we can start keeping track of the performance over time and see the impact of changes more consistently, especially if we always take the performance results of the github actions?

Yeah, that sounds cool, I'll have a look into it. I'll make a new issue for it. Perhaps schedule a call to discuss this a bit further? @Donnype

**Review by ammar92 — COMMENTED** [review]
Looks good in general, with just a few suggestions to improve it even more

**Review by ammar92 — APPROVED** [review]
No more remarks 👍

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
