### PR TITLE
:bug: fix incorrect TLS finding definition

### PR DESCRIPTION
**Pull request by zcrt**
### Changes
Trivial finding definition mistake in TLS version.

---

### Code Checklist
- [x] All the commits in this PR are properly PGP-signed and verified;
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by underdarknl** [comment]
@noamblitz this probably also needs updating in your new Kat-findings branch for the seed data change?

**Comment by dekkers** [comment]
> Looks good. Do we need migrations for this seed change?

No, the upgrade instructions already say that you must load the seed after upgrading.

**Comment by noamblitz** [comment]
So let's wait until new finding types are merged. Finding type information will be removed from rocky db seed and moved to a file hosted on github which is pulled with a boefje.

**Comment by praseodym** [comment]
> So let's wait until new finding types are merged. Finding type information will be removed from rocky db seed and moved to a file hosted on github which is pulled with a boefje.

There is no harm in merging this now, right? And maybe @zcrt needs this to be backported to v1.8?

**Review by ammar92 — APPROVED** [review]

**Review by dekkers — APPROVED** [review]

**Pull request merged**
