### PR TITLE
Add djLint for Rocky templates

### LINKED ISSUE #612: Add djLint pre-commit hook & reformat all templates
Add djlint as pre-commit hook en reformat all templates using djlint.

After merging #626 we still need to fix and enable linting for rules:
- [x] Merge #626
- [x] H006 **ignored**: `img` tag should have `height` and `width` attributes
- [x] H013 https://github.com/minvws/nl-kat-coordination/pull/701
- [x] H014 https://github.com/minvws/nl-kat-coordination/pull/701
- [x] H016 **ignored**: Missing `title` tag in html.
- [x] H017 **ignored**: Tag should be self closing.
- [x] H019 https://github.com/minvws/nl-kat-coordination/pull/701
- [x] H020 https://github.com/minvws/nl-kat-coordination/pull/701
- [x] H023 https://github.com/minvws/nl-kat-coordination/pull/701
- [x] H025 https://github.com/minvws/nl-kat-coordination/pull/701
- [x] H030 **ignored**: Consider adding a meta description.
- [x] H031 **ignored**: Consider adding meta keywords.
- [x] H033 https://github.com/minvws/nl-kat-coordination/pull/701
- [x] T001 https://github.com/minvws/nl-kat-coordination/pull/672
- [x] T002 https://github.com/minvws/nl-kat-coordination/pull/672
- [x] T003 https://github.com/minvws/nl-kat-coordination/pull/672
- [x] T032 https://github.com/minvws/nl-kat-coordination/pull/672

### PR DESCRIPTION
**Pull request by praseodym**
## Changes

Set up pre-commit to lint Rocky templates using djLint and reformat all files using `djlint rocky/*/templates --reformat`.

## Issue ticket number and link

Relates to #612

## Proof

See diff :-)

## Extra instructions for others
_This section may be skipped or omitted. Uncomment and answer the below questions if relevant._

## Checklist for author(s):
- [ ] All the commits in this PR are properly PGP-signed and verified;
- [x] This PR comes from a `feature` or `hotfix` branch, in line with our git branching strategy;
- [x] This PR is "bite-sized" and only focuses on a single issue, problem, or feature;
- [x] I am not reinventing the wheel: there is no high-quality library that already has this feature;
- [x] I have changed the example `.env` files if I added, removed, or changed any config options, and I have informed others that they need to modify their `.env` files if required;
- [x] I have performed a self-review of my own code;
- [x] I have commented my code, particularly in hard-to-understand areas;
- [ ] I have made corresponding changes to the documentation, if necessary;
- [x] I have written unit, integration, and end-to-end tests for the change that I made;

If a non-trivial PR:
- [ ] This PR is part of a milestone and has appropriate labels;
- [ ] This PR is properly linked to the project board (either directly or via an issue);
- [ ] I have added screenshots or some other proof that my code does what it is supposed to do;

```
## Checklist for functional reviewer(s):
- [ ] If a non-trivial PR: This PR is properly linked to an issue on the project board;
- [ ] I have checked out this branch, and successfully ran `make kat`;
- [ ] I have ran `make test-rf` and all end-to-end Robot Framework tests pass;
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended;
- [ ] I confirmed that there are no unintended functional regressions in this branch;

### What works:
* _bullet point + screenshot (if useful) per tested functionality_

### What doesn't work:
* _bullet point + screenshot (if useful) per tested functionality_

### Bug or feature?:
* _bullet point + screenshot (if useful) if it is unclear whether something is a bug or an intended feature._
```

```
## Checklist for code reviewer(s):
- [ ] The code passes the CI tests and linters;
- [ ] The code does not bypass authentication or security mechanisms;
- [ ] The code does not introduce any dependency on a library that has not been properly vetted;
- [ ] The code does not violate Model-View-Template and our other architectural principles;
- [ ] The code contains docstrings, comments, and documentation where needed;
- [ ] The code prioritizes readability over performance where appropriate;
- [ ] The code conforms to our agreed coding standards.
```

### CODE REVIEW

**Review by ammar92 — COMMENTED** [review]
Nice one! I do have config sugestions:
```ini
[tool.djlint]
max_line_length = 120
blank_line_after_tag = "load,extends,include"
preserve_blank_lines = true
```

**Comment by praseodym** [comment]
@ammar92 thanks, I'll add those! I'm also going to ignore "H017 | Tag should be self closing" because the reformat won't fix it and it seems like we've chosen to not use self-closing tags.

**Comment by praseodym** [comment]
It's not easy to create a PR to fix all linting errors at once because djLint can't fix everything automatically, so that means manual fixes will have to be redone for every merge conflict. I propose we disable linting rules that cannot be automatically fixed for now, and then gradually enable and fix them one by one later.

**Comment by ammar92** [comment]
> It's not easy to create a PR to fix all linting errors at once because djLint can't fix everything automatically, so that means manual fixes will have to be redone for every merge conflict. I propose we disable linting rules that cannot be automatically fixed for now, and then gradually enable and fix them one by one later.

That works for now. Another option would be to leave this PR for formatting only and include linting (and its fixes) in another PR. Both are fine so I'll leave it up to you

**Comment by praseodym** [comment]
@ammar92 I removed `preserve_blank_lines = true` from your configuration because it introduced a lot of blank lines (similar to https://github.com/Riverside-Healthcare/djLint/issues/300, which has been closed in the meantime).

**Comment by ammar92** [comment]
> @ammar92 I removed `preserve_blank_lines = true` from your configuration because it introduced a lot of blank lines (similar to [Riverside-Healthcare/djLint#300](https://github.com/Riverside-Healthcare/djLint/issues/300), which has already been closed).

Ah strange, so this behavior isn't already fixed in https://github.com/Riverside-Healthcare/djLint/pull/302?

**Review by dekkers — APPROVED** [review]

**Pull request merged**
