### PR TITLE
Fix loading javascript in Django admin

### PR DESCRIPTION
**Pull request by Rieven**
### Changes
- Js files were not loaded in Django admin, making for example checkbox bulk selection not working. This has to do with that the JS files were not seen as same origin files. Added django admin templates and introduced new template tag to fix this.
 
 ### Issue link
Closes https://github.com/minvws/nl-kat-coordination/issues/1477

### CODE REVIEW

**Comment by dekkers** [comment]
We use nonce because that is the most secure option. The django admin has 7 templates with script tags and if we would want to keep using nonce CSP we have to copy those templates and add the nonce attribute. We would have to update the templates when we upgrade to a new major Django version, but if we stick to the LTS versions the next time we would have to do that is April 2025 so I don't really see that as a big problem.

**Comment by Rieven** [comment]
> We use nonce because that is the most secure option. The django admin has 7 templates with script tags and if we would want to keep using nonce CSP we have to copy those templates and add the nonce attribute. We would have to update the templates when we upgrade to a new major Django version, but if we stick to the LTS versions the next time we would have to do that is April 2025 so I don't really see that as a big problem.

Is it also and idea to add these 7 files to the list instead of "self" or it that as well less secured?

**Comment by dekkers** [comment]
> > We use nonce because that is the most secure option. The django admin has 7 templates with script tags and if we would want to keep using nonce CSP we have to copy those templates and add the nonce attribute. We would have to update the templates when we upgrade to a new major Django version, but if we stick to the LTS versions the next time we would have to do that is April 2025 so I don't really see that as a big problem.
> 
> Is it also and idea to add these 7 files to the list instead of "self" or it that as well less secured?

You can't add django templates to the CSP header because the browser doesn't know about django templates. You can use a decorator in to specify a different CSP header in django-csp, but that also doesn't help us with the admin views.

**Comment by underdarknl** [comment]
Could we upstream this to the django project? It seems like more people would and are going to run into this problem?

**Comment by dekkers** [comment]
> Could we upstream this to the django project? It seems like more people would and are going to run into this problem?

https://code.djangoproject.com/ticket/15727

My guess is that most people don't use the nonce method so don't run into this problem.

**Comment by ammar92** [comment]
If this isn't a huge problem and not getting a lot of attention from Django, perhaps we should close/ archive this PR?

**Comment by dekkers** [comment]
Reopening because we are missing nice to have things in the admin because the javascript doesn't work. The PR already partly fixes the problem, there are few more templates in the django admin that uses javascript however. These are the templates from grepping for script in the django git repository:

- django/contrib/admin/templates/admin/base.html
- django/contrib/admin/templates/admin/change_form.html
- django/contrib/admin/templates/admin/change_list.html
- django/contrib/admin/templates/admin/delete_confirmation.html
- django/contrib/admin/templates/admin/delete_selected_confirmation.html
- django/contrib/admin/templates/admin/popup_response.html
- django/contrib/admin/templates/admin/prepopulated_fields_js.html

I think it would also be nice to add a comment describing why the templates are there and/or linking to this PR.

**Comment by underdarknl** [comment]
While this fixes the 'issue' for now, it introduces a complex update/upgrade path for us. Ideally we still make sure we fix this in the Django project itself, and not just in the scope of our project.
Code beyond that remark looks as I'd expect it to look.

**Comment by Rieven** [comment]
I have tested it and it works as intended.

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
