### PR TITLE
minimal / maximal number of required checboxes checked functionality

### PR DESCRIPTION
**Pull request by underdarknl**
### Changes
Adds functionality to set a min/max required count on checkboxes. Either by setting the required flag and optional min/max attrs on a checkbox itself (which we will use as a reference to find similar named checkboxes), or on any other element in a form, or a form itself. which we will then use to collect all checkboxes in that group.

### Issue link

Closes [#2134](https://github.com/minvws/nl-kat-coordination/issues/2134)

### Demo

---

### Code Checklist
- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have made corresponding changes to the documentation, if necessary.
- [ ] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by ammar92** [comment]
## Checklist for QA:
- [ ] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [ ] I have managed to pass the onboarding flow
    - [ ] Objects and Findings are created properly
    - [ ] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
* It didn't work at first, but then I noticed the wrong form was updated in this implementation. So I fixed this and should be working now (see screenshot)

image


### What doesn't work:
* See above

**Comment by underdarknl** [comment]
There are reasonable voices that told me the customvalidity route (or even form validation as supplied by the browsers in general) is not a11y compatible.

A better route would be to introduce html based error's and validity classes:

https://cloudfour.com/thinks/progressively-enhanced-form-validation-part-3-validating-a-checkbox-group/

**Review by dekkers — APPROVED** [review]

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
- Functionality works however a clearing bug exists as described below. 

### What doesn't work:
n/a


### Bug or feature?:
- The error message is thrown when selecting the object(s) on the row instead of using the 'Select all' checkbox. This situation **only occurs** when you click the 'Setup report' button before you have selected any objects at all. Thus to reproduce this situation:

1. Make sure at least one object has L2 clearance and shows up on the report page.
2. Without selecting any objects, click the 'Setup report' button. You should now see the error message that you haven't selected enough object. 
3. Select one or more objects on the **row** instead of using the 'Select all' checkbox. The error message is thrown again/not cleared. 
4. To bypass this bug you have to use the 'Select all' button. 

The screenshot below shows that the error message will appear when selecting the object on the row:

checkbox-selection

**Comment by underdarknl** [comment]
The described situation was what I expected to have happened before my latest changes. Maybe you where looking at a cached version of the javascript file? I expect that situation to be handled correctly by the version currently in this branch.

**Comment by stephanie0x00** [comment]
The bug is now resolved. Ready for merge.

**Review by dekkers — APPROVED** [review]

**Pull request merged**
