### PR TITLE
Add plugins to findings report

### PR DESCRIPTION
**Pull request by Rieven**
### Changes

Added required and optional plugins for Findings Report

### Issue link

Closes ...

### Demo
image
image

### QA notes

Try to create a Findings Report till plugins are showed.

---

### Code Checklist

- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue.
- [ ] I have written unit tests for the changes or fixes I made.
- [x] I have checked the documentation and made changes where necessary.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

- [x] Tickets have been created for newly discovered issues.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---

## Checklist for code reviewers:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---

## Checklist for QA:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by noamblitz** [comment]
The ssl boefjes all do not generate cve finding types that show up in the report. They should not be required.

**Comment by noamblitz** [comment]
I would say dns-records should also be added.

**Comment by noamblitz** [comment]
nmap-udp should not be required i think

**Comment by noamblitz** [comment]
shodan could be suggested because it generated cve's (I think). Also sorry for al the comments.

**Review by ammar92 — DISMISSED** [review]

**Comment by stephanie0x00** [comment]
> The ssl boefjes all do not generate cve finding types that show up in the report. They should not be required.

Correct that SSL boefjes do not generate CVE findings. The Vulnerability report gives an overview of CVE's only. The Findings report also contains non-CVE findings. Thus SSL boefjes are required for the Findings report.

**Comment by stephanie0x00** [comment]
> shodan could be suggested because it generated cve's (I think). Also sorry for al the comments.

Agreed, Shodan and LeakIX are good suggested plugins.

**Comment by stephanie0x00** [comment]
> nmap-udp should not be required i think

Some open UDP ports should be scanned to get a proper insight into a network/server. As there are some services that could result in nasty security issues if they are open. Such as denial of service attacks, sensitive data exposure. I can type out a list of some very common bad UDP ports. We could also decide to add a boefje that checks for those very specific bad UDP ports and add that to the Findings report instead.

**Comment by noamblitz** [comment]
We could easily add them to the open port but if you send me really bad open udp ports!

**Comment by stephanie0x00** [comment]
## Checklist for QA:

- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
  - [x] I have managed to pass the onboarding flow
  - [x] Objects and Findings are created properly
  - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.
- [x] I checked the logs for errors and/or warnings and made issues where necessary

### What works:
Looks good. The listed mandatory and suggested plugins are now shown. The rocky logs do not show any errors suggesting typos or otherwise weird behaviour. 

### What doesn't work:
n/a

### Bug or feature?:
n/a

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
