### PR TITLE
Refactor Multi Report to comply to the new report flow

### PR DESCRIPTION
**Pull request by Rieven**
### Changes

- Fix the report flow from beginning to end
- Created 2 aggregate reports from 2 organisations.
- Downloaded the aggregate data for both organisations
- Inserted these 2 aggregate data as Report Data in one of the organisations
- Created a Multi report from these 2 aggregate reportData oois.
- removed get requests
- Fix ooi type when no OOI type is filtered.
- Added test for this flow

### Issue link
https://github.com/minvws/nl-kat-coordination/issues/3623

Closes https://github.com/minvws/nl-kat-coordination/issues/3623

### Demo

https://github.com/user-attachments/assets/c06a639f-bd22-4e95-8b71-175f40621284

### QA notes
Upload these 2 report datas from upload raw OOI data:

image

use `openkat/report-data` as mimetype 
choose any random ooi from the dropdown list.

do it for these 2 report data
[aggregate_report_mispo.es.json](https://github.com/user-attachments/files/17542513/aggregate_report_mispo.es.json)
[aggregate_report_minvws.json](https://github.com/user-attachments/files/17542514/aggregate_report_minvws.json)

Then...
Create a multi report and choose these 2 oois.

---

### Code Checklist

- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue.
- [x] I have written unit tests for the changes or fixes I made.
- [x] I have checked the documentation and made changes where necessary.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

- [x] Tickets have been created for newly discovered issues.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---

## Checklist for code reviewers:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---

## Checklist for QA:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by noamblitz** [comment]
When generating a multi org report i get this error

image

**Comment by Rieven** [comment]
> When generating a multi org report i get this error

I wonder why you don't have summary in the report data, as for me:
image

**Comment by noamblitz** [comment]
image
Apparently it gets translated????

**Comment by noamblitz** [comment]
You can see the translation also in your screenshot. Dont know why you'd translate there :)

**Comment by noamblitz** [comment]
Aha, you didnt change that in this PR. Im sorry.

**Comment by Rieven** [comment]
> b2339ae

fixed in: https://github.com/minvws/nl-kat-coordination/pull/3705/commits/b2339ae8f6a0859b33af049da41bd83bf60b6c9f

**Comment by noamblitz** [comment]
Feedback seems to have been implemented correctly. Nice work @Rieven

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
