### PR TITLE
Fix ip address not showing in open ports report

### PR DESCRIPTION
**Pull request by Rieven**
### Changes
Bug: ip adress was a string and could not retrieve `tokenized.address` in template.

### Issue link
https://github.com/minvws/nl-kat-coordination/issues/2679
https://github.com/minvws/nl-kat-coordination/issues/2681

Closes https://github.com/minvws/nl-kat-coordination/issues/2679
Closes https://github.com/minvws/nl-kat-coordination/issues/2681

### Demo
Screenshot 2024-03-19 at 13 59 34

---

### Code Checklist
- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [x] I have written unit tests for the changes or fixes I made.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have made corresponding changes to the documentation, if necessary.
- [x] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Review by ammar92 — DISMISSED** [review]

**Comment by dekkers** [comment]
Some tests are failing

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
The open ports are showing for IPv4 addresses. 

### What doesn't work:
No open ports are shown for IPv6 addresses even though they are open. 

### Bug or feature?:
See point above.

**Comment by Rieven** [comment]
> ## Checklist for QA:
> * [x]  I have checked out this branch, and successfully ran a fresh `make reset`.
> * [x]  I confirmed that there are no unintended functional regressions in this branch:
>   
>   * [x]  I have managed to pass the onboarding flow
>   * [x]  Objects and Findings are created properly
>   * [x]  Tasks are created and completed properly
> * [ ]  I confirmed that the PR's advertised `feature` or `hotfix` works as intended.
> 
> ### What works:
> The open ports are showing for IPv4 addresses.
> 
> ### What doesn't work:
> No open ports are shown for IPv6 addresses even though they are open.
> 
> ### Bug or feature?:
> See point above.

Oww that is strange, then this test should have failed:
https://github.com/minvws/nl-kat-coordination/blob/2b07b3339f2df9d72ec006fe5536e0ca6a40e354/rocky/tests/integration/test_reports.py#L146

**Comment by noamblitz** [comment]
@stephanie0x00, did you enable docker ipv6? Did nmap find the ports as open? Question is whether its a boefje problem or a report problem.

**Comment by noamblitz** [comment]
After adding open ports to the ipv6 manually, the ports are shown correctly in the report. I think the problem is that docker cant communicate over ipv6 out of the box which should always be handled in production environments.

**Comment by Rieven** [comment]
Closed, already fixed.

**Pull request closed without merging**
