### PR TITLE
UUID as organization code

### PR DESCRIPTION
**Pull request by zcrt**
### Changes
Allows UUIDs including four hypens as organization code.

### Demo
image

---

### Code Checklist
- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have made corresponding changes to the documentation, if necessary.
- [ ] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by zcrt** [comment]
Though something in Katalogus seems unhappy

```python
katalogus-1  | Traceback (most recent call last):
katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
katalogus-1  |     await app(scope, receive, sender)
katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
katalogus-1  |     response = await func(request)
katalogus-1  |                ^^^^^^^^^^^^^^^^^^^
katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
katalogus-1  |     raise e
katalogus-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
katalogus-1  |     raw_response = await run_endpoint_function(
--
katalogus-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^
katalogus-1  |   File "/app/boefjes/boefjes/katalogus/routers/organisations.py", line 39, in get_organisation
katalogus-1  |     return storage.get_by_id(organisation_id)
katalogus-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
katalogus-1  |   File "/app/boefjes/boefjes/sql/organisation_storage.py", line 23, in get_by_id
katalogus-1  |     instance = self._db_instance_by_id(organisation_id)
katalogus-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
katalogus-1  |   File "/app/boefjes/boefjes/sql/organisation_storage.py", line 63, in _db_instance_by_id
katalogus-1  |     raise OrganisationNotFound(organisation_id) from ObjectNotFoundException(
katalogus-1  | boefjes.katalogus.storage.interfaces.OrganisationNotFound: 550e8400-e29b-41d4-a716-44665545
katalogus-1  | [2024-03-14 07:40:23 +0000] [9] [INFO] [h11_impl] 172.30.0.7:58878 - "GET /v1/organisations/550e8400-e29b-41d4-a716-44665545 HTTP/1.1" 404
```

**Comment by ammar92** [comment]
@dekkers Does this need a migration since this implementation changes the `max_length` of the slug field?

**Comment by ammar92** [comment]
> I suppose this value should be changed, would you prefer 36 or 64 (or something else)?
> 
> https://github.com/minvws/nl-kat-coordination/blob/cfa6a3374fb4bbb9891e5f2d9a243c358e9785ea/boefjes/boefjes/sql/db_models.py#L18
> 
> and probably here as well:
> 
> https://github.com/minvws/nl-kat-coordination/blob/1eaca4b4cb449300ce00dfb76dcf40db05a2d271/bytes/bytes/database/db_models.py#L14

And the Rocky model you're changing

**Comment by dekkers** [comment]
This would indeed need to be changed in a lot of places and some of those would need database migrations. 

I'm also missing a rationale why this change is needed. The organization code is meant to be a short human readable code/slug indicating the organization that can be used in the url, logging, database, etc.

**Comment by underdarknl** [comment]
Im guessing Z-CERT's internal database carries UUID's for each organization.  Synchronizing them between the two worls would be useful, however it means a lot of internal changes for our systems, frontends, backends etc. And why limit this sync to just organization-codes, or to the way Z-cert handles them internally.
I think a more meaningful way would be to have an 'external-reference' field for items that might exists in two databases.

**Comment by zcrt** [comment]
I don't think I have enough knowledge of the internal workings of OpenKAT to add this field in a meaningful way, maybe @dekkers can help?

**Comment by underdarknl** [comment]
The Organization model lives here:

https://github.com/minvws/nl-kat-coordination/blob/4375b6a02621146d9f57f0986f8aa330ae65726f/rocky/tools/models.py#L81

You can add a new field named 'external_indentifier' or something similar.
Django will then prompt to run database migrations and add the needed database changes and admin options. From there you could add the new field to various api's and screens where needed.

**Comment by zcrt** [comment]
I look at this with @underdarknl, adding an `external_identifier` field results in multiple database changes as well. This is because the External Database boefje does not have knowledge about any other organisation fields, except for the ID. Nevertheless, our internal system can handle UUIDs without the URN hyphens, which means that the problem that this PR tries to solve, can be solved by using UUIDs without URN hyphens as organisation code.

**Pull request closed without merging**
