### PR TITLE
Improve system identification

### PR DESCRIPTION
**Pull request by dekkers**
### Changes
This is partly some changes already done on the aggregate report branch. I've also pushed those changes there, but I'm opening a seperate PR so we can have discussion about it if necessary.

This adds some more service mappings. HTTP was missing, meaning that every website was classified as both "other" via services and as "web" via Website OOI. It also doesn't classify the system as "other" if it isn't listed in software mapping, because classifying everything that isn't dicom as "other" doesn't make much sense to me.

I've also removed some services that I either can't find in the nmap services file (tsdns, smtp-stats, smtp-proxy, mail-admin), can't find what it is so probably old and irrelevant (mailq) or is something different than normal DNS (mdns).

I also sort the list of services so they are always in the same order.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Review by Donnype — DISMISSED** [review]
Unless we say that we should ignore the http services in favor of the Website OOI (@noamblitz ?): LGTM!

**Comment by noamblitz** [comment]
Website OOI is better/more future proof. But this is more consistent. So im fine with this.

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
Onboarding flow works as expected. Can enable boefjes that scan as intended. Have generated the system report and it looks good. 

### What doesn't work:
- System type for IPv6 hosts.

### Bug or feature?:
N/a.

**Comment by noamblitz** [comment]
Does your ipv6 have ipservices/ipports?

**Comment by stephanie0x00** [comment]
Yep. I scanned various domains which all have IPv4 and IPv6 enabled. No output is shown for the IPv6 hosts.

**Comment by noamblitz** [comment]
I mean, did nmap scan this ipv6 address and did it find open ports with services. System recognition works with ipservices. If the ipv6 is not scanned, or if there are no open ports found (for example because nmap runs in Docker), then it wont recognise any systems.

**Comment by underdarknl** [comment]
> I mean, did nmap scan this ipv6 address and did it find open ports with services. System recognition works with ipservices. If the ipv6 is not scanned, or if there are no open ports found (for example because nmap runs in Docker), then it wont recognise any systems.

**Comment by noamblitz** [comment]
We discussed, and this is indeed the case

**Comment by stephanie0x00** [comment]
I know it's an docker connectivity issue. I have the required fixes locally to enable docker for main which I'll push.

**Comment by dekkers** [comment]
The issue I had was that just giving the OpenKAT containers IPv6 via docker compose is not enough. The boefje will start its own container using API call to the docker socket and that container also needs IPv6. If I configure containers to have IPv6 by default using https://docs.docker.com/config/daemon/ipv6/#use-ipv6-for-the-default-bridge-network then nmap will work and I will also see system types for IPv6 hosts:

image

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
