### PR TITLE
add meta / cache hash for rpki boefje to raw output

### PR DESCRIPTION
**Pull request by underdarknl**
Adds the hash of the rpki source file to the meta file, and adds the meta file to the boefje raw output for storage in bytes / consumption in Octopoes.

### Changes
Adds the hash of the rpki source file uses for this boefje run, or creates a new hash when new rpki source data is downloaded.
The hash and metadata is then also stored i bytes for safe keeping and timestamping purposes.

### Code Checklist
- [ ] All the commits in this PR are properly PGP-signed and verified;
- [ ] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [ ] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Review by ammar92 — DISMISSED** [review]
Looks good to me. I wanted to suggest to use `hashlib.algorithms_guaranteed` for input validation. However, since the user input is already validated using the JSON schema, this won't be necessary.

**Comment by underdarknl** [comment]
> Looks good to me. I wanted to suggest to use `hashlib.algorithms_guaranteed` for input validation. However, since the user input is already validated using the JSON schema, this won't be necessary.

Yes, I wanted to make sure the user does select a weak or broken algo like sha1 or md5.

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [ ] I confirmed that there are no unintended functional regressions in this branch:
    - [ ] I have managed to pass the onboarding flow
    - [ ] Objects and Findings are created properly
    - [ ] Tasks are created and completed properly
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
Can pass onboarding flow. 

### What doesn't work:
The RPKI boefje is missing from the katalogus, thus cannot test. I do see the normalizer. 

rpki


### Bug or feature?:
n/a

**Comment by stephanie0x00** [comment]
RPKI boefje now runs, and 2 json files are created. However 2 small bugs were found: 

```
{"vrps_records": [{"prefix": "195.135.195.0/24", "expires": "2023-12-22T06:01", "ta": "ripe"}], "valid": false, "exists": true}
```

1. The 'valid' tag should be called 'not-expired', as it doesn't qualify as a validity check. 

1. Possibly the cache is expired as the ROA is not expired. See: https://bgp.he.net/net/195.135.195.0/24#_netinfo

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
RPKI seems to work as expected now. Onboarding can be passed, RPKI boefje can be enabled and runs. The label in the json files has been changed. 

### What doesn't work:
- Current RPKI boefje doesn't perform any signing checks, it only checks if a key is present and if this isn't expired. 
- The corresponding finding is still named "KAT-INVALID-RPKI" instead of "KAT-NOTEXPIRED-RPKI". This should still be changed.

Separate tickets can be created if those are not picked up for this PR. 

### Bug or feature?:
n/a.

**Comment by underdarknl** [comment]
Lets do a separate PR for clarifying the not-valid / non-expired finding, as this would also trigger changes in the reports that consume these findings.

A separate boefje would also be needed to verify if once's upstream provider checks for RKPI validity and blocks any invalid or expired routes.

**Review by dekkers — APPROVED** [review]

**Pull request merged**
