### PR TITLE
Fix/pin pydicom dependency and revert irrelevant version bumps

### PR DESCRIPTION
**Pull request by Donnype**
### Changes

Revert unnecessary version bumps from https://github.com/minvws/nl-kat-coordination/pull/3536 and pin transitive dependency `pydicom`.

### Issue link

Closes https://github.com/minvws/nl-kat-coordination/issues/3551

### Demo

-

### QA notes

Should resolve the behavior described in https://github.com/minvws/nl-kat-coordination/issues/3551.

---

### Code Checklist

- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue.
- [x] I have written unit tests for the changes or fixes I made.
- [x] I have checked the documentation and made changes where necessary.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

---

## Checklist for code reviewers:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---

## Checklist for QA:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by stephanie0x00** [comment]
## Checklist for QA:

- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
  - [x] I have managed to pass the onboarding flow
  - [x] Objects and Findings are created properly
  - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.
- [x] I checked the logs for errors and/or warnings and made issues where necessary

### What works:
This fixed the errors in the logs. The DICOM boefje also runs against an IP address (there is no real DICOM server, thus cannot check if it actually parses correctly). Can be merged once Review is complete.

### What doesn't work:
n/a

### Bug or feature?:
n/a

**Review by ammar92 — COMMENTED** [review]
Unfortunately, several dependencies (e.g., `certifi`) have been downgraded. I suggest reverting the `pyproject.toml` and `poetry.lock` files and then following these steps:
- `poetry add pydicom@latest`
- `make poetry-dependencies`
- stage poetry.lock, pyproject.toml and the requirements*.txt files

**Comment by Donnype** [comment]
@ammar92 this was intentional, as the latest pydicom breaks our setup and this sets the other requirements back to the version of this Monday

**Comment by ammar92** [comment]
> @ammar92 this was intentional, as the latest pydicom breaks our setup and this sets the other requirements back to the version of this Monday

Clear, then it should be `poetry add pydantic@2.4.4` instead

**Review by ammar92 — APPROVED** [review]

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
