### PR TITLE
Add uvicorn back as non-dev dependency

### PR DESCRIPTION
**Pull request by Donnype**
### Changes
Aims to fix this CI issue: https://github.com/minvws/nl-kat-coordination/actions/runs/6967803150/job/18960606486

---

### Code Checklist
- [x] All the commits in this PR are properly PGP-signed and verified;
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [x] I have written unit tests for the changes or fixes I made.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Review by ammar92 — DISMISSED** [review]

**Review by dekkers — COMMENTED** [review]
This doesn't seem to fix the problem:
https://github.com/minvws/nl-kat-coordination/actions/runs/7030897949/job/19131674661

You can manually run the workflow by going to actions, choose "Test installing the debian packages" on the left. You then end up at https://github.com/minvws/nl-kat-coordination/actions/workflows/test_debian_packages_on_ubuntu.yml and can run the workflow using the "Run workflow" button on that page.

**Comment by dekkers** [comment]
I don't understand why uvicorn is removed as dependency. PR #1976 has no mention on why this is done, but it seems wrong to me and I think the correct fix would be adding the dependency back.

**Comment by jpbruinsslot** [comment]
> I don't understand why uvicorn is removed as dependency. PR #1976 has no mention on why this is done, but it seems wrong to me and I think the correct fix would be adding the dependency back.

Indeed this is the case

**Comment by dekkers** [comment]
This works now:

https://github.com/minvws/nl-kat-coordination/actions/runs/7031355363/job/19132973364

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
