### PR TITLE
underscore broke the pdf engine (again)

### PR DESCRIPTION
**Pull request by tobiasBDO**
### Changes
The `"recommendation": "Implement TLS_FALLBACK_SCSV."` in the rocky database seed breaks the LaTeX engine due to the special character `_` being unsanitized. Changing this to `-` allows Keiko to not crash when the `KATFindingType|KAT-NO-TLS-FALLBACK-SCSV` gets reported.

### Proof
```
Underfull \hbox (badness 4819) in paragraph at lines 8877--8878
keiko_1                | []|\OT1/phv/m/n/10.95 The en-cryp-ted con-nec-tion pro-vi-des no pro-tec-tion
keiko_1                | ! Missing $ inserted.
keiko_1                | <inserted text>
keiko_1                |                 $
keiko_1                | l.8883                         Aanbeveling & Implement TLS_
keiko_1                |                                       FALLBACK_SCSV. \\
keiko_1                | ! Missing $ inserted.
keiko_1                | <inserted text>
keiko_1                |                 $
keiko_1                | l.8884
```

---

### Code Checklist
- [x] All the commits in this PR are properly PGP-signed and verified;
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [ ] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by underdarknl** [comment]
Shoudn't we just escape these strings on ingestion into the latex engine?

**Comment by tobiasBDO** [comment]
> Shoudn't we just escape these strings on ingestion into the latex engine?

There already is code for that in place, just not sure how this was able to be passed without sanitization.
This is present in the keiko.py.

```python

LATEX_SPECIAL_CHARS = str.maketrans(
    {
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\^{}",
        "\\": r"\textbackslash{}",
        "\n": "\\newline%\n",
        "-": r"{-}",
        "\xA0": "~",  # Non-breaking space
        "[": r"{[}",
        "]": r"{]}",
    }
)
```

**Comment by praseodym** [comment]
I agree that we should escape this string properly. We currently don't escape all strings because we use LaTeX markup in some strings as well, there is an issue to change that (#999) so we can escape it properly.

I'll check if we can escape a bit more to at least fix this issue.

**Comment by praseodym** [comment]
Just checked, and the recommendation string is escaped in the template:
https://github.com/minvws/nl-kat-coordination/blob/5d6b4b8b3ccfc78311689418c8ee4d0070d29145/keiko/templates/bevindingenrapport/template.tex#L159-L161

@tobiasBDO considering you customised the templates, can you confirm that the `|latexescape` is also there in your template?

**Comment by tobiasBDO** [comment]
> Just checked, and the recommendation string is escaped in the template:
> 
> https://github.com/minvws/nl-kat-coordination/blob/5d6b4b8b3ccfc78311689418c8ee4d0070d29145/keiko/templates/bevindingenrapport/template.tex#L159-L161
> 
> @tobiasBDO considering that you customised the templates, can you confirm that the `|latexescape` is also there in your template?

I checked it out and that is indeed the case, my bad.
Sorry for the fuss!

**Pull request closed without merging**
