### PR TITLE
Handle an empty plugin.consumes field for the plugin detail page

### PR DESCRIPTION
**Pull request by Donnype**
### Changes
This was an old ticket that was not handled properly yet. It was time to clean this up as I believe there are boefjes in the pipeline without input ooi that may appear in the Katalogus.

### Issue link

Closes https://github.com/minvws/nl-kat-coordination/issues/348

### Proof
After removing the `consumes` elements manually in `kat_binaryedge/boefje.json` as an example:

image

---

### Code Checklist
- [x] All the commits in this PR are properly PGP-signed and verified;
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [x] I have written unit tests for the changes or fixes I made.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by Donnype** [comment]
@HeleenSG Maybe you can have a quick look at this one as well? :)

**Comment by underdarknl** [comment]
N.B. binaryedge does consume objects. This is just an example screenshot.

**Review by HeleenSG — APPROVED** [review]
Approval for design & Ux changes.

**Comment by Darwinkel** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
* No apparent regressions

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
