### PR TITLE
Cache found boefjes and normalizers

### PR DESCRIPTION
**Pull request by dekkers**
### Changes
When running boefjes/normalizers from the command line with debug logging turned on I saw that boefjes/normalizers directories were repeatedly scanned. This PR caches the found boefjes and normalizers and makes sure we only do this once.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by underdarknl** [comment]
I think we should do this on production envs, but not necessarily on environments where people are developing (eg, debug=True for lack of a better env flag signaling development purposes). Adding a new plugin would require a restart of the katalogus service when this is merged, which makes the development learning curve steeper.

**Review by ammar92 — COMMENTED** [review]
Looks good 👍

**Comment by ammar92** [comment]
> I think we should do this on production envs, but not necessarily on environments where people are developing (eg, debug=True for lack of a better env flag signaling development purposes). Adding a new plugin would require a restart of the katalogus service when this is merged, which makes the development learning curve steeper.

Fair point. But to be honest, even in a development environment and within this context, I would still prefer to restart/ rebuild the service, just to have a deterministic environment.

**Comment by Darwinkel** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
* No apparent regressions (but no obvious performance increase either)

**Review by underdarknl — APPROVED** [review]

**Comment by Donnype** [comment]
I think this was a premature optimization

**Pull request merged**
