### PR TITLE
Fixes for empty tables

### LINKED ISSUE #3843: Bulk actions visible when report history is empty
**Describe the bug**
The bulk actions are visible even though the report history table is empty.

**To Reproduce**

1. Do a "make reset"
2. Check the report history table

**Expected behavior**
Action button shouldn't be visible when the report history table is empty.

**Screenshots**
Image

**OpenKAT version**
main

### PR DESCRIPTION
**Pull request by madelondohmen**
### Changes
- Removes the bulk action button when the report history table is empty
- Removes the empty findings table on the Crisis Room page and replace with an empty state text

The format of the code has changed, which might make the changed files hard to understand.
The only things I've added are if-statements around the tables to check if there's data

### Issue link

Closes #3843 

### Demo
afbeelding

afbeelding

### QA notes
- Do a make reset
- Check the crisis room --> Table shouldn't be visible, but instead you should see an empty state text
- Check the report history page --> Bulk action button shoudn't be visible

---

### Code Checklist

- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue.
- [ ] I have written unit tests for the changes or fixes I made.
- [x] I have checked the documentation and made changes where necessary.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

- [ ] Tickets have been created for newly discovered issues.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---

## Checklist for code reviewers:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---

## Checklist for QA:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by ppvg** [comment]
Are "findings" found? Or would something like "no findings have been made yet" make more sense?

**Comment by madelondohmen** [comment]
> Are "findings" found? Or would something like "no findings have been made yet" make more sense?

@ppvg This is the same text that we use in the Findings Report when there's no data. 
@stephanie0x00 What do you think about this? If we want to change it, we should change it everywhere.

**Review by ammar92 — APPROVED** [review]

**Comment by TwistMeister** [comment]
## Checklist for QA:

- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
  - [x] I have managed to pass the onboarding flow
  - [x] Objects and Findings are created properly
  - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.
- [x] I checked the logs for errors and/or warnings and made issues where necessary

### What works:

The 2 listed scenario's work

### Bug or feature?:

- The "Crisis room" across all organizations still shows 2 "empty" (count = 0) tables instead of text. Not sure if intended?

Screenshot 2024-11-19 at 14 31 22

**Comment by stephanie0x00** [comment]
> > Are "findings" found? Or would something like "no findings have been made yet" make more sense?
> 
> @ppvg This is the same text that we use in the Findings Report when there's no data. @stephanie0x00 What do you think about this? If we want to change it, we should change it everywhere.

We should definitely update the text. It is quite complicated and nuanced though. For now we can update it to: "No findings have been identified yet.". We probably have to type out the nuances on the docs and make a reference to this page from the reports.

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
