### PR TITLE
Latex docs keiko

### PR DESCRIPTION
**Pull request by tobiasBDO**
### Changes
Introduction of docs for the customization of Keiko reports, as communicated in the issue

### Issue link
https://github.com/minvws/nl-kat-coordination/issues/592

---

### Code Checklist
- [ ] All the commits in this PR are properly PGP-signed and verified;
- [ ] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [ ] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Review by praseodym — DISMISSED** [review]
Nice addition! I've added some missing backticks as required by reStructuredText.

**Comment by tobiasBDO** [comment]
> Nice addition! I've added some missing backticks as required by reStructuredText.

Thanks, didn't know this markup was different from markdown. I've committed your missing backticks.😄

**Review by ammar92 — DISMISSED** [review]
Looks good! Only a newline is missing at the end of `latex.rst`

**Comment by praseodym** [comment]
@tobiasBDO can you run [`pre-commit`](https://pre-commit.com)? The CI still complains about a missing newline at the end of the file.

**Comment by tobiasBDO** [comment]
Okay, I had some trouble due to Windows not liking the `boefjes/boefjes/plugin_repository/test/images/test-bit-1:01` paths. I accidentally made a commit without GPG and my identity. Fixed this in the last commit but now CLA is not satisfied.

**Comment by praseodym** [comment]
You can try an [interactive rebase](https://docs.github.com/en/get-started/using-git/using-git-rebase-on-the-command-line) followed by a force push (`git push -f`) to remove the offending commit.

**Comment by tobiasBDO** [comment]
> You can try an [interactive rebase](https://docs.github.com/en/get-started/using-git/using-git-rebase-on-the-command-line) followed by a force push (`git push -f`) to remove the offending commit.

The commit history is very ugly, but I've been able to fix this. All the checks are passing.

**Review by ammar92 — APPROVED** [review]

**Review by dekkers — APPROVED** [review]

**Review by praseodym — APPROVED** [review]

**Review by underdarknl — APPROVED** [review]

**Comment by tobiasBDO** [comment]
Fully signed PR in https://github.com/minvws/nl-kat-coordination/pull/983.

**Pull request closed without merging**
