### PR TITLE
fix rpki delete_on_close, can be just delete

### PR DESCRIPTION
**Pull request by underdarknl**
### Changes
change delete_on_close into just delete

https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile states we can just use delete:
`Therefore to use the name of the temporary file to reopen the file after closing it, either make sure not to delete the file upon closure (set the delete parameter to be false)`

We for some reason saw the following error when running the previous version:
`TypeError: NamedTemporaryFile() got an unexpected keyword argument 'delete_on_close'`

### Code Checklist
- [ ] All the commits in this PR are properly PGP-signed and verified;
- [ ] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [ ] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [ ] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [ ] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Review by ammar92 — APPROVED** [review]
Using `os.rename` for moving files might be a bit obscure. A nicer approach would be using `shutil.copy` and allowing NamedTemporaryFile to handle closure and file deletion automatically

**Comment by dekkers** [comment]
> Using `os.rename` for moving files might be a bit obscure. A nicer approach would be using `shutil.copy` and allowing NamedTemporaryFile to handle closure and file deletion automatically

Copying is not atomic and would introduce a race condition again, that's why we need to use rename because rename is an atomic operation so that we will never see an empty or half written file.

**Comment by dekkers** [comment]
> We for some reason saw the following error when running the previous version:
> `TypeError: NamedTemporaryFile() got an unexpected keyword argument 'delete_on_close'`

The last line says: `Changed in version 3.12: Added delete_on_close parameter.`

**Comment by ammar92** [comment]
> > Using `os.rename` for moving files might be a bit obscure. A nicer approach would be using `shutil.copy` and allowing NamedTemporaryFile to handle closure and file deletion automatically
> 
> Copying is not atomic and would introduce a race condition again, that's why we need to use rename because rename is an atomic operation so that we will never see an empty or half written file.

Clear. I misread that the destination was a file instead of a directory. I'll put a comment above the `rename` call to clear it up.

**Comment by ammar92** [comment]
Pushed some fixes:
- Wrong argument type for `json.write`)
- JSON file gets created and updated correctly

**Comment by ammar92** [comment]
## Checklist for QA:
- [ ] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [ ] I have managed to pass the onboarding flow
    - [ ] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
* Boefje runs and updates the data and meta file accordingly
* Normalizer runs

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
Onboarding flow can be passed.
RPKI boefje can be started again and runs as expected.
RPKI report shows the change of the "RPKI not expired"

### What doesn't work:
N/a

### Bug or feature?:
Likely unrelated to this PR, but noticed that the DNS report of the onboarding flow doesn't count the values anymore, e.g. for a domain I get 3 medium findings in the Findings tab, but no vulnerabilities are shown on the DNS summary report.This is also happening on the current main (commit 18ee8e616bc0036a296d2b2b7d202d40bc2da075 (HEAD -> main, tag: v1.14.0rc1, origin/release-1.14, origin/main, origin/HEAD))

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
Onboarding flow can be passed.
RPKI boefje can be started again and runs as expected.
RPKI report shows the change of the "RPKI not expired"

### What doesn't work:
N/a

### Bug or feature?:
n/a

**Review by dekkers — APPROVED** [review]

**Pull request merged**
