### PR TITLE
Stop yielding network in certain normalizers

### PR DESCRIPTION
**Pull request by originalsouth**
### Changes
Stop yielding network in certain normalizers

### Issue link
N/A

### Demo
N/A

### QA notes
No specific changes in flow, good to check the affected normalizers (Nmap TCP). 

---

### Code Checklist

- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue.
- [ ] I have written unit tests for the changes or fixes I made.
- [x] I have checked the documentation and made changes where necessary.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

- [x] Tickets have been created for newly discovered issues.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---

## Checklist for code reviewers:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---

## Checklist for QA:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Review by ammar92 — APPROVED** [review]
I believe there's another one in `boefjes/boefjes/plugins/kat_burpsuite/normalize.py`

**Review by noamblitz — APPROVED** [review]

**Comment by noamblitz** [comment]
> I believe there's another one in `boefjes/boefjes/plugins/kat_burpsuite/normalize.py`

That one could possibly stay there since burp has no input OOI

**Comment by underdarknl** [comment]
> We should also use the network of the input OOI instead of hardcoding "internet" in kat_crt_sh, but that can also be done in a later PR.

CRT.sh records can only ever be 'about' the internet, so not hardcoding it to that network wouldn't really change anything

**Review by underdarknl — APPROVED** [review]

**Comment by originalsouth** [comment]
@Donnype what is point of assigning this PR to me after it is merged?

**Pull request merged**
