### PR TITLE
strip appending dot from records to avoid duplicates

### PR DESCRIPTION
**Pull request by tobiasBDO**
## Changes
Add `rstrip(".")` to ensure no double OOI's are raised during default onboarding behavior. The toplevels such as `.nl` and `.net` are still being raised duplicate as `Hostname` also appended with the dot. I don't know if that is something that should be fixed as well, or just excluded. Love to hear what you guys think!

image

### before
image

### after
image

## Extra instructions for others
_This section may be skipped or omitted. Uncomment and answer the below questions if relevant._

## Checklist for author(s):
- [x] All the commits in this PR are properly PGP-signed and verified;
- [x] This PR comes from a `feature` or `hotfix` branch, in line with our git branching strategy;
- [x] This PR is "bite-sized" and only focuses on a single issue, problem, or feature;
- [x] I am not reinventing the wheel: there is no high-quality library that already has this feature;
- [ ] I have changed the example `.env` files if I added, removed, or changed any config options, and I have informed others that they need to modify their `.env` files if required;
- [x] I have performed a self-review of my own code;
- [ ] I have commented my code, particularly in hard-to-understand areas;
- [ ] I have made corresponding changes to the documentation, if necessary;
- [ ] I have written unit, integration, and end-to-end tests for the change that I made;

If a non-trivial PR:
- [ ] This PR is part of a milestone and has appropriate labels;
- [ ] This PR is properly linked to the project board (either directly or via an issue);
- [ ] I have added screenshots or some other proof that my code does what it is supposed to do;

```
## Checklist for functional reviewer(s):
- [ ] If a non-trivial PR: This PR is properly linked to an issue on the project board;
- [ ] I have checked out this branch, and successfully ran `make kat`;
- [ ] I have ran `make test-rf` and all end-to-end Robot Framework tests pass;
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended;
- [ ] I confirmed that there are no unintended functional regressions in this branch;

### What works:
* _bullet point + screenshot (if useful) per tested functionality_

### What doesn't work:
* _bullet point + screenshot (if useful) per tested functionality_

### Bug or feature?:
* _bullet point + screenshot (if useful) if it is unclear whether something is a bug or an intended feature._
```

```
## Checklist for code reviewer(s):
- [ ] The code passes the CI tests and linters;
- [ ] The code does not bypass authentication or security mechanisms;
- [ ] The code does not introduce any dependency on a library that has not been properly vetted;
- [ ] The code does not violate Model-View-Template and our other architectural principles;
- [ ] The code contains docstrings, comments, and documentation where needed;
- [ ] The code prioritizes readability over performance where appropriate;
- [ ] The code conforms to our agreed coding standards.
```

### CODE REVIEW

**Comment by underdarknl** [comment]
I think that for the time being, (where we cannot yet easily filter out duplicate findings) or 'similar' websites we should move to not having duplicate hostnames either. The changes of finding other findings on a website with a trailing dot, as compared to the website without the trailing dot do not weigh up to the double findings in the reports for now.
I'd also like this to be backported to 1.7.

In the future we can start doing deduplication in the reports / queries, as the differentiation between websites is something that does carry value. The same goes for deduplication of subdomains like www and non www pointing to the same website. And findings on url's that are fixed in most installations by changing the server config instead of every url itself.

**Review by Darwinkel — APPROVED** [review]
## Checklist for functional reviewer(s):
- [ ] If a non-trivial PR: This PR is properly linked to an issue on the project board;
- [x] I have checked out this branch, and successfully ran `make kat`;
- [ ] I have ran `make test-rf` and all end-to-end Robot Framework tests pass;
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended;
- [x] I confirmed that there are no unintended functional regressions in this branch;

Note: the Boefje unit test assertions should be fixed.

### What works:
* There do not appear to be any regressions
* There are no OOI's with trailing dots

### What doesn't work:
* `null`

### Bug or feature?:
* In my tests, top-level domains are correctly stripped. I cannot reproduce any duplicates.

**Comment by noamblitz** [comment]
I am afraid many bits will fail because of this since they place findings on the fqdn. Needs thorough testing

**Comment by Darwinkel** [comment]
I've been thoroughly testing this, and I found that Website objects were no longer created. The culprit is possibly here in the `dns_resolving.py` bit.

image

From what I gather, this if-statement causes a cascading side effect: ResolvedHostnames are not created -> HTTPResources are not created -> Websites are not created. 

Commenting that if-statement appears to resolve the issue.

**Comment by noamblitz** [comment]
It seems that spf, dmarc and dkim findings are not created since they are only created on the fqdn

**Comment by underdarknl** [comment]
https://github.com/minvws/nl-kat-coordination/pull/675 replaced this PR because it is more in line with how the rest of the system works.

**Pull request closed without merging**
