### PR TITLE
Remove more then 1 active state on menu items

### PR DESCRIPTION
**Pull request by Rieven**
### Changes
- Put active state on menu based on url name instead of finding menu name in url path.

### Issue link
https://github.com/minvws/nl-kat-coordination/issues/1157

Closes https://github.com/minvws/nl-kat-coordination/issues/1157

### Proof
image

---

### Code Checklist
- [x] All the commits in this PR are properly PGP-signed and verified;
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by Darwinkel** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
* Fix works as intended
* No apparent regressions

**Comment by Rieven** [comment]
> **Regression:** _While this fix solves the problem of getting two active states at once, it doesn't account for "sub" pages of a subject. They don't get the active state until we register conditions on URL-names for all existing URL's._
> 
> That's not scalable and maintainable. So instead it would be nice if we refactor all URL-names so that the subject is added as prefix to the name. For example: `plugin_detail` should become `katalogus_plugin_detail`. Then we can check for `"katalogus_"` being part of the `url_name`

We can also add a `namespace` for all urls that belongs to a group of urls, like all findings or object details.

**Comment by Rieven** [comment]
> **Regression:** _While this fix solves the problem of getting two active states at once, it doesn't account for "sub" pages of a subject. They don't get the active state until we register conditions on URL-names for all existing URL's._
> 
> That's not scalable and maintainable. So instead it would be nice if we refactor all URL-names so that the subject is added as prefix to the name. For example: `plugin_detail` should become `katalogus_plugin_detail`. Then we can check for `"katalogus_"` being part of the `url_name`

I have changed it to incorporate menu url to be part of extended url path. This means that we also must concatenate urls from this point of view.

**Comment by TwistMeister** [comment]
While your latest fix works a lot better, there's still a few cases where the `url_name` isn't yet suited to the check you're doing. For example, the following pages still don't highlight the corresponding menu item properly:
http://localhost:8000/en/dev/finding_type/add/
http://localhost:8000/en/dev/scans/
http://localhost:8000/en/dev/upload/raw/
http://localhost:8000/en/dev/upload/csv/
http://localhost:8000/en/dev/indemnifications/

**Comment by Rieven** [comment]
[ ] http://localhost:8000/en/dev/finding_type/add/

**Comment by ammar92** [comment]
Is this one still in progress or ready to review/ test?

**Comment by Rieven** [comment]
> Is this one still in progress or ready to review/ test?

This one can be merged for me.

**Comment by Darwinkel** [comment]
I went through the entire interface and all relevant pages appear to have a single appropriate active state. Nice.

**Review by dekkers — APPROVED** [review]

**Pull request merged**
