### PR TITLE
Clear cache before wp-scan

### PR DESCRIPTION
**Pull request by noamblitz**
Clear the cache before scanning wp-scan

### CODE REVIEW

**Comment by noamblitz** [comment]
Probably needs to be backported to 1.8 and 1.9?

**Comment by underdarknl** [comment]
I am confused as to why the container seems to be storing caches between runs. Wouldn't it be reset to default every time we re-run the container if we configure it correctly regardless of what the code in there does?

**Comment by noamblitz** [comment]
I would also think that, but after seeing behavior that can only be explained by caching and finding this flag in their docker docs, this should be the fix. It is currently being tested, will update it here asap.

**Comment by ammar92** [comment]
This is indeed highly unusual when running containers without volumes attached. Therefore I suspect it's not actually data that is causing this, but a side effect caused by the `--clear-cache` option that results in different behavior. If we're sure this is a real solution, we should accept it with some reluctance for now.

**Comment by noamblitz** [comment]
It seems that this did not resolve the problem.

**Pull request closed without merging**
