### PR TITLE
Support a Schedule without a schedule in scheduler

### PR DESCRIPTION
**Pull request by jpbruinsslot**
### Changes

Support for setting a `Schedule` without a `schedule`. This was already supported, however, this wasn't exposed in the API. The `schedule`  field was required.

This supports scheduling a task without a `schedule` , meaning a one-off scheduled task

### Issue link

Related: https://github.com/minvws/nl-kat-coordination/issues/3753

### QA notes

_Please add some information for QA on how to test the newly created code._

---

### Code Checklist

- [x] All the commits in this PR are properly PGP-signed and verified.
- [x] This PR only contains functionality relevant to the issue.
- [x] I have written unit tests for the changes or fixes I made.
- [x] I have checked the documentation and made changes where necessary.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

- [ ] Tickets have been created for newly discovered issues.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [ ] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have included comments in the code to elaborate on what is not self-evident from the code itself, including references to issues and discussions online, or implicit behavior of an interface.

---

## Checklist for code reviewers:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---

## Checklist for QA:

Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by underdarknl** [comment]
So, that would just be a delayed job then, right?

**Comment by jpbruinsslot** [comment]
> So, that would just be a delayed job then, right?

where you specify when it needs to run

**Review by ammar92 — APPROVED** [review]

**Comment by stephanie0x00** [comment]
## Checklist for QA:

- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
  - [x] I have managed to pass the onboarding flow
  - [x] Objects and Findings are created properly
  - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.
- [x] I checked the logs for errors and/or warnings and made issues where necessary

### What works:
Scheduled tasks run

### What doesn't work:
n/a

### Bug or feature?:
- Rescheduling a tasks results in an Error in the interface, but no errors in the scheduler logs. 
- 
image

**Comment by jpbruinsslot** [comment]
Fixed the issue found in QA

**Comment by stephanie0x00** [comment]
Confirm! Rescheduling works now. Rescheduling of reports works too. :+1:

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
