### PR TITLE
Remove support for Python 3.8 and 3.9

### PR DESCRIPTION
**Pull request by dekkers**
### Changes
We don't need to support Python 3.8 and 3.9 anymore. Python 3.10 makes typing a lot nicer and this makes it possible to use that. I haven't updated all the typing code beause I think it would be better to do that in a separate PR after this one is merged.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Review by underdarknl — COMMENTED** [review]
Changes look good, I approve of this change, however we need to do QA on the small python change / deps.

**Comment by originalsouth** [comment]
@dekkers mostly out of curiosity, why are we opting for 3.10 instead of 3.11?

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [ ] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [ ] Objects and Findings are created properly
    - [ ] Tasks are created and completed properly
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
To test this PR I've completely removed all existing docker containers in the QA environment, as to make sure all docker containers are freshly rebuild with these changes. In the past we've had some problems with docker containers not properly rebuilding after running 'make reset' and thus requiring a manual rebuild of the container. 

- Onboarding flow works including its DNS report. 
- In de Katalogus I've enabled all boefjes that do not require either an API key or additional configuration (E.g. specifying ports for nmap). 
- Adding multiple object manually and setting the clearance to L4 to ensure that all boefjes can be tested. 
- Tasks seem to be generated as expected. 
- Created a dump from all the docker logs and searched for warnings and errors to check if some things were missed in the background.
- Tried to generate a normal report, which seems to work. 

Functional wise I haven't run into any issues yet.
### What doesn't work:
N/a

### Bug or feature?:
The error logs do show some warnings and errors. I'm not sure if these are related to the removal of python or not. I'll forward the logs to @dekkers so he can make that judgement call. Otherwise it's ready for merge I'd say.

**Comment by dekkers** [comment]
I don't think they are related to this PR, because I don't really change any code and the docker-compose.yml development environment was already using Python 3.11 and that isn't changed. To be sure we should reproduce the errors on main. As far as I can see there are 3 different problems:

- security_txt_downloader gets a `certificate verify failed: IP address mismatch, certificate is not valid`. I don't know if this is new or not. It might be caused by the recent update of forcediphttpsadapter. 

- Octopoes has a very large number of the following errors, #2403 might be the cause of that:
```
nl-kat-coordination-octopoes_api_worker-1  | [2024-02-08 20:10:02 +0000] [10] [INFO] [ooi_repository] Could not deserialize value [value=Service|http]
```

- Boefje runner can't find the input object of a task in octopoes, a number of the following exceptions:
```nl-kat-coordination-boefje-1  | Traceback (most recent call last):
nl-kat-coordination-boefje-1  |   File "/app/boefjes/boefjes/app.py", line 248, in _start_working
nl-kat-coordination-boefje-1  |     handler.handle(p_item.data)
nl-kat-coordination-boefje-1  |   File "/app/boefjes/boefjes/job_handler.py", line 143, in handle
nl-kat-coordination-boefje-1  |     _find_ooi_in_past(
nl-kat-coordination-boefje-1  |   File "/app/boefjes/boefjes/job_handler.py", line 54, in _find_ooi_in_past
nl-kat-coordination-boefje-1  |     raise ObjectNotFoundException(f"Object {reference} not found in Octopoes")
nl-kat-coordination-boefje-1  | octopoes.models.exception.ObjectNotFoundException: Object ... not found in Octopoes
```

**Comment by noamblitz** [comment]
Boefje runner can't find the input object of a task in octopoes, a number of the following exceptions:

I have been able to reproduce this Exception a couple of times. I've noticed a pattern where this Exception mostly occurs with near-empty queues. I have looked at the code and came to a possible reason. I think that the event of the new ooi triggers the scheduler to schedule the boefje **before** the new ooi actually exists in octopoes which triggers the ObjectNotFound.

**Comment by stephanie0x00** [comment]
Alright, shall we make new tickets for the other two issues and then merge this ticket?

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
