### PR TITLE
Remove IPs with zero vulnerabilities

### PR DESCRIPTION
**Pull request by madelondohmen**
### Changes
This code removes IPs with zero vulnerabilities from both the Aggregate Report and the side menu. This modification is implemented in preparation for reports containing a large number of IPs, enhancing the readability of both the chapter and the side menu.

### Issue link
Closes https://github.com/minvws/nl-kat-coordination/issues/2321

### Demo
Before:
afbeelding

After:
afbeelding

---

### Code Checklist
- [x] All the commits in this PR are properly PGP-signed and verified;
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [ ] I have written unit tests for the changes or fixes I made.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_code.md) into your comment.

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](https://github.com/minvws/nl-kat-coordination/blob/main/docs/source/templates/pull_request_template_review_qa.md) into your comment.

### CODE REVIEW

**Comment by underdarknl** [comment]
Lets see what Z-cert thinks about this before merging.

**Review by ammar92 — APPROVED** [review]
Looks good to me

**Comment by zcrt** [comment]
Update looks good, though I would prefer `IPaddressV4|internet|</adres>` to be replaced with something like `hostname(s) (IPaddress(es)), though that may be a separate issue

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
Onboarding flow works, findings and tasks are created and scheduled as expected. 
Empty IPs are not shown in the report, so ready for merge. 

### What doesn't work:
Unrelated bug, see below. 

### Bug or feature?:
When adding an object with L2 it appears not to show up on the objects list on the Report flow page. When changing the clearance to L3 it shows up, when changing it back to L2 it remains in the list.

**Comment by noamblitz** [comment]
Ive added https://github.com/minvws/nl-kat-coordination/issues/2321 to the description of the PR

**Review by underdarknl — APPROVED** [review]

**Pull request merged**
